#!/usr/bin/env node

/**
 * Report Exporter
 *
 * Exports context optimizer reports as Markdown or HTML
 * for sharing or archiving.
 */

import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync } from 'fs';
import { join, basename } from 'path';
import { homedir } from 'os';

const DATA_DIR = join(homedir(), '.claude-context-optimizer');
const SESSIONS_DIR = join(DATA_DIR, 'sessions');
const GLOBAL_STATS_FILE = join(DATA_DIR, 'global-stats.json');
const EXPORTS_DIR = join(DATA_DIR, 'exports');

mkdirSync(EXPORTS_DIR, { recursive: true });

function loadJSON(file) {
  if (!existsSync(file)) return null;
  return JSON.parse(readFileSync(file, 'utf-8'));
}

function formatTokens(n) {
  if (n >= 1000000) return `${(n / 1000000).toFixed(1)}M`;
  if (n >= 1000) return `${(n / 1000).toFixed(1)}K`;
  return String(n);
}

function exportMarkdown() {
  const stats = loadJSON(GLOBAL_STATS_FILE);
  if (!stats || stats.totalSessions === 0) {
    console.log('No data to export.');
    return;
  }

  const date = new Date().toISOString().split('T')[0];
  let md = `# Context Optimizer Report — ${date}\n\n`;

  md += `## Overview\n\n`;
  md += `| Metric | Value |\n|--------|-------|\n`;
  md += `| Sessions tracked | ${stats.totalSessions} |\n`;
  md += `| Total tokens | ${formatTokens(stats.totalTokensTracked)} |\n`;
  md += `| Tokens wasted | ${formatTokens(stats.estimatedTokensSaved)} |\n`;
  md += `| Waste ratio | ${stats.totalTokensTracked > 0 ? Math.round((stats.estimatedTokensSaved / stats.totalTokensTracked) * 100) : 0}% |\n`;
  md += `| Avg tokens/session | ${formatTokens(stats.avgTokensPerSession)} |\n\n`;

  // Session history table
  if (stats.sessionHistory && stats.sessionHistory.length > 0) {
    md += `## Recent Sessions\n\n`;
    md += `| Date | Files | Reads | Edits | Waste % |\n|------|-------|-------|-------|---------|\n`;
    for (const s of stats.sessionHistory.slice(-20)) {
      const d = new Date(s.date).toLocaleDateString();
      md += `| ${d} | ${s.filesRead} | ${s.totalReads} | ${s.totalEdits} | ${s.wastePercent}% |\n`;
    }
    md += '\n';
  }

  // Top files
  if (stats.topWastedFiles && stats.topWastedFiles.length > 0) {
    md += `## Top Wasted Files\n\n`;
    md += `| File | Tokens Wasted | Sessions |\n|------|--------------|----------|\n`;
    for (const f of stats.topWastedFiles.slice(0, 10)) {
      md += `| \`${basename(f.fullPath)}\` | ${formatTokens(f.totalTokensWasted)} | ${f.sessions} |\n`;
    }
    md += '\n';
  }

  if (stats.topUsefulFiles && stats.topUsefulFiles.length > 0) {
    md += `## Top Useful Files\n\n`;
    md += `| File | Edits | Reads | Sessions |\n|------|-------|-------|----------|\n`;
    for (const f of stats.topUsefulFiles.slice(0, 10)) {
      md += `| \`${basename(f.fullPath)}\` | ${f.totalEdits} | ${f.totalReads} | ${f.sessions} |\n`;
    }
    md += '\n';
  }

  md += `---\n*Generated by [claude-context-optimizer](https://github.com/egorfedorov/claude-context-optimizer)*\n`;

  const outFile = join(EXPORTS_DIR, `report-${date}.md`);
  writeFileSync(outFile, md);
  console.log(`Exported to: ${outFile}`);
  return outFile;
}

function exportHTML() {
  const stats = loadJSON(GLOBAL_STATS_FILE);
  if (!stats || stats.totalSessions === 0) {
    console.log('No data to export.');
    return;
  }

  const date = new Date().toISOString().split('T')[0];
  const overallWaste = stats.totalTokensTracked > 0 ?
    Math.round((stats.estimatedTokensSaved / stats.totalTokensTracked) * 100) : 0;

  // Build sparkline data from session history
  const sparkData = (stats.sessionHistory || []).slice(-30).map(s => s.wastePercent);

  let html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Context Optimizer Report — ${date}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, 'SF Mono', 'Fira Code', monospace; background: #0d1117; color: #c9d1d9; padding: 2rem; }
  .container { max-width: 900px; margin: 0 auto; }
  h1 { color: #58a6ff; margin-bottom: 0.5rem; font-size: 1.5rem; }
  h2 { color: #8b949e; margin: 2rem 0 1rem; font-size: 1.1rem; text-transform: uppercase; letter-spacing: 0.05em; }
  .subtitle { color: #8b949e; margin-bottom: 2rem; }
  .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin: 1.5rem 0; }
  .card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1.2rem; }
  .card .label { color: #8b949e; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; }
  .card .value { color: #f0f6fc; font-size: 1.8rem; font-weight: 700; margin-top: 0.3rem; }
  .card .sub { color: #8b949e; font-size: 0.8rem; margin-top: 0.2rem; }
  .card.waste .value { color: ${overallWaste > 40 ? '#f85149' : overallWaste > 20 ? '#d29922' : '#3fb950'}; }
  table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
  th { text-align: left; color: #8b949e; font-size: 0.75rem; text-transform: uppercase; padding: 0.5rem; border-bottom: 1px solid #30363d; }
  td { padding: 0.5rem; border-bottom: 1px solid #21262d; font-size: 0.85rem; }
  tr:hover { background: #161b22; }
  .bar { display: inline-block; height: 8px; border-radius: 4px; }
  .bar-useful { background: #3fb950; }
  .bar-waste { background: #f85149; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 0.7rem; font-weight: 600; }
  .badge-good { background: #0d3117; color: #3fb950; }
  .badge-warn { background: #2d1a00; color: #d29922; }
  .badge-bad { background: #3d0a0a; color: #f85149; }
  .sparkline { display: flex; align-items: end; gap: 2px; height: 40px; margin: 1rem 0; }
  .spark-bar { width: 8px; border-radius: 2px 2px 0 0; min-height: 2px; }
  footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #30363d; color: #484f58; font-size: 0.75rem; }
</style>
</head>
<body>
<div class="container">
  <h1>Context Optimizer Report</h1>
  <p class="subtitle">Generated ${date}</p>

  <div class="cards">
    <div class="card">
      <div class="label">Sessions</div>
      <div class="value">${stats.totalSessions}</div>
    </div>
    <div class="card">
      <div class="label">Total Tokens</div>
      <div class="value">${formatTokens(stats.totalTokensTracked)}</div>
      <div class="sub">~$${((stats.totalTokensTracked / 1000000) * 15).toFixed(2)} on Opus</div>
    </div>
    <div class="card waste">
      <div class="label">Waste Ratio</div>
      <div class="value">${overallWaste}%</div>
      <div class="sub">${formatTokens(stats.estimatedTokensSaved)} tokens</div>
    </div>
    <div class="card">
      <div class="label">Avg / Session</div>
      <div class="value">${formatTokens(stats.avgTokensPerSession)}</div>
    </div>
  </div>

  <h2>Waste Trend (last ${sparkData.length} sessions)</h2>
  <div class="sparkline">
    ${sparkData.map(v => {
      const h = Math.max(2, Math.round((v / 100) * 40));
      const color = v > 40 ? '#f85149' : v > 20 ? '#d29922' : '#3fb950';
      return `<div class="spark-bar" style="height:${h}px;background:${color}" title="${v}%"></div>`;
    }).join('\n    ')}
  </div>

  ${stats.topWastedFiles && stats.topWastedFiles.length > 0 ? `
  <h2>Top Wasted Files</h2>
  <table>
    <tr><th>File</th><th>Tokens Wasted</th><th>Sessions</th><th>Impact</th></tr>
    ${stats.topWastedFiles.slice(0, 10).map(f => {
      const maxWaste = Math.max(...stats.topWastedFiles.map(x => x.totalTokensWasted));
      const barW = Math.round((f.totalTokensWasted / maxWaste) * 200);
      return `<tr>
        <td><code>${basename(f.fullPath)}</code></td>
        <td>${formatTokens(f.totalTokensWasted)}</td>
        <td>${f.sessions}</td>
        <td><span class="bar bar-waste" style="width:${barW}px"></span></td>
      </tr>`;
    }).join('\n    ')}
  </table>` : ''}

  ${stats.topUsefulFiles && stats.topUsefulFiles.length > 0 ? `
  <h2>Top Useful Files</h2>
  <table>
    <tr><th>File</th><th>Edits</th><th>Reads</th><th>Sessions</th><th>Impact</th></tr>
    ${stats.topUsefulFiles.slice(0, 10).map(f => {
      const maxUse = Math.max(...stats.topUsefulFiles.map(x => x.usefulness));
      const barW = Math.round((f.usefulness / maxUse) * 200);
      return `<tr>
        <td><code>${basename(f.fullPath)}</code></td>
        <td>${f.totalEdits}</td>
        <td>${f.totalReads}</td>
        <td>${f.sessions}</td>
        <td><span class="bar bar-useful" style="width:${barW}px"></span></td>
      </tr>`;
    }).join('\n    ')}
  </table>` : ''}

  <footer>
    Generated by <a href="https://github.com/egorfedorov/claude-context-optimizer" style="color:#58a6ff">claude-context-optimizer</a>
  </footer>
</div>
</body>
</html>`;

  const outFile = join(EXPORTS_DIR, `report-${date}.html`);
  writeFileSync(outFile, html);
  console.log(`Exported to: ${outFile}`);
  return outFile;
}

const format = process.argv[2] || 'md';

switch (format) {
  case 'md':
  case 'markdown':
    exportMarkdown();
    break;
  case 'html':
    exportHTML();
    break;
  default:
    console.log('Usage: cco-export [md|html]');
}
